version: "3.9"

services:
    backend:
        build: ./backend
        container_name: backend
        ports:
            - "3000:3000"
        environment:
            MONGO_DB_USER: $MONGO_DB_USER
            MONGO_DB_PASS: $MONGO_DB_PASS
            MONGO_DB_CLUSTER: $MONGO_DB_CLUSTER

    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - "8080:8080"
